export const enum CanonicalCLIInstructions {
    BUY_CREATOR_COIN = "buy-creator-coin",
    CHECK_KEY = "check-key",
    GET_SINGLE_PROFILE = "single-profile",
    GET_FOLLOWS_STATELESS = "follows-stateless",
    GET_USERS_STATELESS = "users-stateless",
    GLOBAL_FEED = "global-feed",
    MAX_POSTS = "max-posts",
    INDEX_GLOBAL_FEED = "index-global-feed",
    SUBMIT_POST = "submit-post",
    SUBMIT_TRANSACTION = "submit-transaction",
    UPLOAD_IMAGE = "upload-image",
    SINGLE_POST = "single-post",
    LIKE_POST = "like-post",
    NOTIFICATIONS = "notifications",
    HODLRS = "hodlrs",
    EXCHANGE_RATE = "exchange_rate",
    SEND_DIAMOND = "send_diamond",
    TIKTOKURL = "tiktok_url"
}