/* 
Contains all the friendly route names for the application.
*/
export const enum CanonicalRoutes {
    // Standard Routes
    routePathBlockPublicKey = '/api/v0/block-public-key',
    routePathBuyOrSellCreatorCoin = '/api/v0/buy-or-sell-creator-coin',
    routePathCreateFollowTxnStateless = '/api/v0/create-follow-txn-stateless',
    routePathCreateLikeStateless = '/api/v0/create-like-stateless',
    routePathDeleteIdentities = '/api/v0/delete-identities',
    routePathExchangeBitcoin = '/api/v0/exchange-bitcoin',
    routePathExchangerate = '/api/v0/get-exchange-rate',
    routePathGetAppState = '/api/v0/get-app-state',
    routePathGetBlockTemplate = '/api/v0/get-block-template',
    routePathGetDiamondsForPost = '/api/v0/get-diamonds-for-post',
    routePathGetDiamondsForPublicKey = '/api/v0/get-diamonds-for-public-key',
    routePathGetDiamondedPosts = '/api/v0/get-diamonded-posts',
    routePathGetFollowsStateless = '/api/v0/get-follows-stateless',
    routePathGetHodlersForPublicKey = '/api/v0/get-hodlers-for-public-key',
    routePathGetHotFeed = '/api/v0/get-hot-feed',
    routePathGetJumioStatusForPublicKey = '/api/v0/get-jumio-status-for-public-key',
    routePathGetLikesForPost = '/api/v0/get-likes-for-post',
    routePathGetMessagesStateless = '/api/v0/get-messages-stateless',
    routePathGetNotifications = '/api/v0/get-notifications',
    routePathGetPostsForPublicKey = '/api/v0/get-posts-for-public-key',
    routePathGetPostsStateless = '/api/v0/get-posts-stateless',
    routePathGetProfiles = '/api/v0/get-profiles',
    routePathGetPublicKeyForUsername = '/api/v0/get-public-key-for-user-name',
    routePathGetQuoterepostsForPost = '/api/v0/get-quote-reposts-for-post',
    routePathGetrepostsForPost = '/api/v0/get-reposts-for-post',
    routePathGetSingleProfile = '/api/v0/get-single-profile',
    routePathGetSingleProfilePicture = '/api/v0/get-single-profile-picture',
    routePathGetTxn = '/api/v0/get-txn',
    routePathGetUnreadNotificationsCount = '/api/v0/get-unread-notifications-count',
    routePathGetUsernameForPublicKey = '/api/v0/get-user-name-for-public-key',
    routePathGetUserGlobalMetadata = '/api/v0/get-user-global-metadata',
    routePathGetUserMetadata = '/api/v0/get-user-metadata',
    routePathGetSinglePost = '/api/v0/get-single-post',
    routePathGetUsersStateless = '/api/v0/get-users-stateless',
    routePathMarkContactMessagesread = '/api/v0/mark-contact-messages-read',
    routePathMinerControl = '/api/v0/miner-control',
    routePathSendDiamonds = '/api/v0/send-diamonds',
    routePathSendMessageStateless = '/api/v0/send-message-stateless',
    routePathMarkAllMessagesread = '/api/v0/mark-all-messages-read',
    routePathSetNotificationMetadata = '/api/v0/set-notification-metadata',
    routePathSendDeSo = '/api/v0/send-deso',
    routePathSendPhoneNumberVerificationText = '/api/v0/send-phone-number-verification-text',
    routePathStartOrSkipTutorial = "/api/v0/start-or-skip-tutorial",
    routePathSubmitPhoneNumberVerificationCode = '/api/v0/submit-phone-number-verification-code',
    routePathSubmitPost = '/api/v0/submit-post',
    routePathSubmitTransaction = '/api/v0/submit-transaction',
    routePathTransferCreatorCoin = '/api/v0/transfer-creator-coin',
    routePathUpdateProfile = '/api/v0/update-profile',
    routePathUpdateUserGlobalMetadata = '/api/v0/update-user-global-metadata',
    routePathUploadImage = '/api/v0/upload-image',
    routePathresendVerifyEmail = "/api/v0/resend-verify-email",
    routePathVerifyEmail = "/api/v0/verify-email",
    routePathCompleteTutorial = "/api/v0/complete-tutorial",
    routePathGetTutorialCreators = "/api/v0/get-tutorial-creators",
    routePathUpdateTutorialStatus = "/api/v0/update-tutorial-status",
  
    // Media
    routePathGetVideoStatus = "/api/v0/get-video-status",
    routePathUploadVideo = "/api/v0/upload-video",
  
    // NFT routes.
    routePathCreateNft = "/api/v0/create-nft",
    routePathUpdateNFT = "/api/v0/update-nft",
    routePathCreateNFTBid = "/api/v0/create-nft-bid",
    routePathAcceptNFTBid = "/api/v0/accept-nft-bid",
    routePathGetNFTBidsForNFTPost = "/api/v0/get-nft-bids-for-nft-post",
    routePathGetNFTsForUser = "/api/v0/get-nfts-for-user",
    routePathGetNFTBidsForUser = "/api/v0/get-nft-bids-for-user",
    routePathGetNFTShowcase = "/api/v0/get-nft-showcase",
    routePathGetNextNFTShowcase = "/api/v0/get-next-nft-showcase",
    routePathGetNFTCollectionSummary = "/api/v0/get-nft-collection-summary",
    routePathGetNFTEntriesForPostHash = "/api/v0/get-nft-entries-for-nft-post",
    routePathTransferNFT = "/api/v0/transfer-nft",
    routePathAcceptNFTTransfer = "/api/v0/accept-nft-transfer",
    routePathBurnNFT = "/api/v0/burn-nft",
  
    // ETH
    routePathSubmitETHTx = "/api/v0/submit-eth-tx",
    routePathQueryETHrPC = "/api/v0/query-eth-rpc",
  
    // Admin routes.
    NodeControlroute = "/api/v0/admin/node-control",
    reprocessBitcoinBlockroute = "/api/v0/admin/reprocess-bitcoin-block",
    routePathSwapIdentity = "/api/v0/admin/swap-identity",
    routePathAdminUpdateUserGlobalMetadata = "/api/v0/admin/update-user-global-metadata",
    routePathAdminGetAllUserGlobalMetadata = "/api/v0/admin/get-all-user-global-metadata",
    routePathAdminGetUserGlobalMetadata = "/api/v0/admin/get-user-global-metadata",
    routePathAdminUpdateGlobalFeed = "/api/v0/admin/update-global-feed",
    routePathAdminPinPost = "/api/v0/admin/pin-post",
    routePathAdminremoveNilPosts = "/api/v0/admin/remove-nil-posts",
    routePathAdminGetMempoolStats = "/api/v0/admin/get-mempool-stats",
    routePathAdminGrantVerificationBadge = "/api/v0/admin/grant-verification-badge",
    routePathAdminremoveVerificationBadge = "/api/v0/admin/remove-verification-badge",
    routePathAdminGetVerifiedUsers = "/api/v0/admin/get-verified-users",
    routePathAdminGetUserAdminData = "/api/v0/admin/get-user-admin-data",
    routePathAdminGetUsernameVerificationAuditLogs = "/api/v0/admin/get-username-verification-audit-logs",
    routePathUpdateGlobalParams = "/api/v0/admin/update-global-params",
    routePathSetUSDCentsToDeSoreserveExchangerate = "/api/v0/admin/set-usd-cents-to-deso-reserve-exchange-rate",
    routePathGetUSDCentsToDeSoreserveExchangerate = "/api/v0/admin/get-usd-cents-to-deso-reserve-exchange-rate",
    routePathSetBuyDeSoFeeBasisPoints = "/api/v0/admin/set-buy-deso-fee-basis-points",
    routePathGetBuyDeSoFeeBasisPoints = "/api/v0/admin/get-buy-deso-fee-basis-points",
    routePathAdminGetGlobalParams = "/api/v0/admin/get-global-params",
    routePathGetGlobalParams = "/api/v0/get-global-params",
    routePathEvictUnminedBitcoinTxns = "/api/v0/admin/evict-unmined-bitcoin-txns",
    routePathGetWyreWalletOrdersForPublicKey = "/api/v0/admin/get-wyre-wallet-orders-for-public-key",
    routePathAdminGetNFTDrop = "/api/v0/admin/get-nft-drop",
    routePathAdminUpdateNFTDrop = "/api/v0/admin/update-nft-drop",
    routePathAdminresetJumioForPublicKey = "/api/v0/admin/reset-jumio-for-public-key",
    routePathAdminUpdateJumioDeSo = "/api/v0/admin/update-jumio-deso",
    routePathAdminUpdateTutorialCreators = "/api/v0/admin/update-tutorial-creators",
    routePathAdminresetTutorialStatus = "/api/v0/admin/reset-tutorial-status",
    routePathAdminGetTutorialCreators = "/api/v0/admin/get-tutorial-creators",
    routePathAdminJumioCallback = "/api/v0/admin/jumio-callback",
    routePathAdminGetUnfilteredHotFeed = "/api/v0/admin/get-unfiltered-hot-feed",
    routePathAdminGetHotFeedAlgorithm = "/api/v0/admin/get-hot-feed-algorithm",
    routePathAdminUpdateHotFeedAlgorithm = "/api/v0/admin/update-hot-feed-algorithm",
    routePathAdminUpdateHotFeedPostMultiplier = "/api/v0/admin/update-hot-feed-post-multiplier",
    routePathAdminUpdateHotFeedUserMultiplier = "/api/v0/admin/update-hot-feed-user-multiplier",
    routePathAdminGetHotFeedUserMultiplier = "/api/v0/admin/get-hot-feed-user-multiplier",
  
    // referral program admin routes.
    routePathAdminCreatereferralHash = "/api/v0/admin/create-referral-hash",
    routePathAdminGetAllreferralInfoForUser = "/api/v0/admin/get-all-referral-info-for-user",
    routePathAdminUpdatereferralHash = "/api/v0/admin/update-referral-hash",
    routePathAdminDownloadreferralCSV = "/api/v0/admin/download-referral-csv",
    routePathAdminDownloadrefereeCSV = "/api/v0/admin/download-referee-csv",
    routePathAdminUploadreferralCSV = "/api/v0/admin/upload-referral-csv",
  
    // referral program non-admin routes
    routePathGetreferralInfoForUser = "/api/v0/get-referral-info-for-user",
    routePathGetreferralInfoForreferralHash = "/api/v0/get-referral-info-for-referral-hash",
  
    routePathGetFullTikTokUrL = "/api/v0/get-full-tiktok-url",
  
    // Wyre routes.
    routePathGetWyreWalletOrderQuotation = "/api/v0/get-wyre-wallet-order-quotation",
    routePathGetWyreWalletOrderreservation = "/api/v0/get-wyre-wallet-order-reservation",
  
    // Onboarding routes
    routePathSubscribeToOnboardingEmails = "/api-internal/v0/onboarding-email-subscription",
}